"use client";

import { useState } from "react";
import VibeForm from "../components/VibeForm";
import SpecPreview from "../components/SpecPreview";
import TrackList from "../components/TrackList";
import ErrorDisplay from "../components/ErrorDisplay";
import { PlaylistSpec, Track } from "../types";
import { fetchWithRetry, getErrorMessage } from "../lib/fetch-retry";

export default function Home() {
  const [spec, setSpec] = useState<PlaylistSpec | null>(null);
  const [vibe, setVibe] = useState<string>("");
  const [tracks, setTracks] = useState<Track[]>([]);
  const [selectedUris, setSelectedUris] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [playlistGenerated, setPlaylistGenerated] = useState(false);
  const [playlistUrl, setPlaylistUrl] = useState<string | null>(null);
  const [currentVibeId, setCurrentVibeId] = useState<string | null>(null);

  // generic helper to handle all api calls with retry logic and error handling
  async function apiCall(
    url: string,
    body: object,
    onSuccess: (data: Record<string, unknown>) => void
  ) {
    setLoading(true);
    setError("");

    try {
      const res = await fetchWithRetry(
        url,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(body),
        },
        {
          maxRetries: 3,
          onRetry: (attempt, max) =>
            setError(`Retrying (${attempt}/${max})...`),
        }
      );

      const contentType = res.headers.get("content-type");
      if (!contentType?.includes("application/json")) {
        throw new Error("Invalid server response");
      }

      const data = await res.json();
      if (res.ok) {
        onSuccess(data);
        setError("");
      } else {
        setError(data.error || "Request failed");
      }
    } catch (e) {
      console.error(`API call to ${url} failed:`, e);
      setError(getErrorMessage(e));
    } finally {
      setLoading(false);
    }
  }

  // user types vibe → translate to music specs via llm → save to db
  async function handleVibeTranslate(vibeInput: string) {
    setSpec(null);
    setTracks([]);
    setSelectedUris([]);
    setVibe(vibeInput);
    setPlaylistGenerated(false);
    setCurrentVibeId(null);

    await apiCall("/api/translate", { vibe: vibeInput }, (data) => {
      setSpec(data.spec as PlaylistSpec);
      setCurrentVibeId(data.vibeId as string);
    });
  }

  // user tweaks sliders → update spec → reset playlist state
  function handleSpecChange(nextSpec: PlaylistSpec) {
    setSpec(nextSpec);
    setPlaylistGenerated(false);
  }

  // spec ready → search spotify with llm-generated strategy → return ranked tracks
  async function handleGeneratePlaylist() {
    if (!spec) return;
    setTracks([]);
    setSelectedUris([]);

    await apiCall("/api/discover", { spec, vibe }, (data) => {
      setTracks(data.tracks as Track[]);
      setPlaylistGenerated(true);
    });
  }

  // track checkboxes toggled → save selected uris
  function handleSelectionChange(uris: string[]) {
    setSelectedUris(uris);
  }

  // user clicks post playlist → create on spotify → save to db → return url
  async function handlePostPlaylist() {
    if (selectedUris.length === 0) {
      setError("Please select at least one track");
      return;
    }

    await apiCall(
      "/api/playlist",
      {
        name: `${vibe} Playlist`,
        description: "Generated by Persona DJ",
        uris: selectedUris,
        vibeId: currentVibeId,
      },
      (data) => {
        setPlaylistUrl(data.url as string);
        console.log("✅ Playlist created:", data.url);
      }
    );
  }

  return (
    <div className="flex flex-col md:flex-row gap-8 min-h-[80vh] w-full max-w-6xl mx-auto py-12 px-4">
      {/* Left panel: VibeForm for vibe input and translation */}
      <section className="flex-1 flex flex-col gap-6">
        <VibeForm onTranslate={handleVibeTranslate} loading={loading} />

        {/* Error display with retry button */}
        {error && (
          <ErrorDisplay
            type="error"
            message={error}
            onRetry={
              error.includes("Retrying")
                ? undefined
                : () => {
                    if (vibe && !spec) handleVibeTranslate(vibe);
                    else if (spec && !playlistGenerated)
                      handleGeneratePlaylist();
                    else if (selectedUris.length > 0) handlePostPlaylist();
                  }
            }
          />
        )}

        {/* SpecPreview panel, shown after spec is set */}
        {spec && (
          <>
            <SpecPreview value={spec} onSpecChange={handleSpecChange} />
            {/* Generate Playlist button */}
            <button
              onClick={handleGeneratePlaylist}
              disabled={playlistGenerated || loading}
              className={`w-full py-3 px-4 rounded-lg font-semibold transition-colors ${
                playlistGenerated || loading
                  ? "bg-gray-300 text-gray-500 cursor-not-allowed"
                  : "bg-blue-600 text-white hover:bg-red-700"
              }`}
            >
              {loading
                ? "Generating..."
                : playlistGenerated
                ? "Playlist Generated"
                : "Generate Playlist"}
            </button>
          </>
        )}
      </section>
      {/* Right panel: TrackList and states */}
      <aside className="flex-1 bg-gray-950 border border-gray-800 rounded-lg p-6 overflow-auto min-h-[200px]">
        <h2 className="text-lg font-semibold mb-4 text-white">Tracks</h2>

        {/* Success message when playlist is created */}
        {playlistUrl && (
          <div className="mb-4 p-3 bg-green-900 border border-green-700 rounded-lg">
            <p className="text-green-200 font-semibold">
              ✅ Playlist created successfully!
            </p>
            <a
              href={playlistUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-green-400 hover:text-green-300 underline text-sm"
            >
              Open in Spotify →
            </a>
          </div>
        )}

        {tracks.length > 0 && (
          <TrackList
            tracks={tracks}
            selectedUris={selectedUris}
            onSelectionChange={handleSelectionChange}
            onPostPlaylist={handlePostPlaylist}
            postingPlaylist={loading && selectedUris.length > 0}
          />
        )}
        {!loading && !error && tracks.length === 0 && (
          <pre className="text-sm text-green-400 whitespace-pre-wrap">
            {/* Show spec JSON if available, else placeholder */}
            {spec
              ? JSON.stringify(spec, null, 2)
              : "// Your playlist JSON will appear here"}
          </pre>
        )}
      </aside>
    </div>
  );
}
